# _config.yml

remote_theme: "jekyll/minima"

plugins:
  - jekyll-remote-theme

minima:
  skin: auto
  show_excerpts: false
  hide_site_feed_link: true

title: Xiangwan's GitHub
show_downloads: false
