# _config.yml

# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/slate@v0.2.0
remote_theme: pages-themes/minima@v2.5.2

plugins:
  - jekyll-remote-theme

title: Xiangwan's GitHub Pages
show_downloads: false
