name: Update RuleFiles
on:
  schedule:
    - cron: '22 22 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  copy-links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git configuration
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Download files
      run: |
        mkdir -p Rules
        echo "Rules/Lan.list|https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Lan/Lan.list" > rule_file_links.list
        echo "Rules/Direct.list|https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Direct/Direct.list" >> rule_file_links.list
        echo "Rules/Hijacking.list|https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Hijacking/Hijacking.list" >> rule_file_links.list
        echo "Rules/Privacy.list|https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Privacy/Privacy.list" >> rule_file_links.list
        echo "Rules/WeChat.list|https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/WeChat/WeChat.list" >> rule_file_links.list
        echo "Rules/Telegram.list|https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Telegram/Telegram.list" >> rule_file_links.list
        echo "Rules/OpenAI.list|https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/OpenAI/OpenAI.list" >> rule_file_links.list
        echo "Rules/Copilot.list|https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Copilot/Copilot.list" >> rule_file_links.list
        echo "Rules/Gemini.list|https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Gemini/Gemini.list" >> rule_file_links.list
        echo "Rules/Claude.list|https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Claude/Claude.list" >> rule_file_links.list
        echo "Rules/Apple.list|https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Apple/Apple.list" >> rule_file_links.list
        echo "Rules/Microsoft.list|https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Microsoft/Microsoft.list" >> rule_file_links.list
        echo "Rules/Google.list|https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Google/Google.list" >> rule_file_links.list
        echo "Rules/GlobalMedia.list|https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/GlobalMedia/GlobalMedia.list" >> rule_file_links.list
        echo "Rules/Global.list|https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Global/Global.list" >> rule_file_links.list
        echo "Rules/ChinaMedia.list|https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/ChinaMedia/ChinaMedia.list" >> rule_file_links.list
        echo "Rules/China.list|https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/ChinaNoMedia/ChinaNoMedia.list" >> rule_file_links.list
        MAX_RETRIES=3
        while IFS='|' read -r filepath url; do
          echo "Downloading: $url -> $filepath"
          attempt=1
          while [ $attempt -le $MAX_RETRIES ]; do
            curl -fsS -o "$filepath" "$url" && break
            echo "Download failed. Retrying ($attempt/$MAX_RETRIES)..."
            attempt=$((attempt+1))
            sleep 3
          done
        done < rule_file_links.list

    - name: Clean up rule files
      run: |
        find Rules -type f -name "*.list" | while read -r file; do
          grep -v '^# AUTHOR' "$file" | grep -v '^# REPO' > cleaned_file.tmp
          mv cleaned_file.tmp "$file"
        done

    - name: Generate Ai.list
      run: |
        echo "# AI Rules Collection" > Rules/Ai.list
        echo "" >> Rules/Ai.list && cat Rules/OpenAI.list >> Rules/Ai.list
        echo "" >> Rules/Ai.list && cat Rules/Copilot.list >> Rules/Ai.list
        echo "" >> Rules/Ai.list && cat Rules/Gemini.list >> Rules/Ai.list
        echo "" >> Rules/Ai.list && cat Rules/Claude.list >> Rules/Ai.list
        echo "" >> Rules/Ai.list && cat Rules/Grok.list >> Rules/Ai.list

    - name: Commit & copy RuleFiles
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
        message: 'Update RuleFiles'
        add: 'Rules/*'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
