name: Update RewriteFiles
on:
  schedule:
    - cron: '5 0 * * *'
  workflow_dispatch:
jobs:
  copy-links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Git configuration
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - name: Download files
      run: |
        mkdir -p Rewrite/JavaScript
        LINK="https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/chongxie.txt"
        curl -fsS -o "Rewrite/Chongxie.conf" "$LINK" || true
        YT_MODULE="https://raw.githubusercontent.com/iab0x00/ProxyRules/main/Rewrite/YouTubeNoAd.sgmodule"
        curl -fsS -o "Rewrite/YouTubeNoAd.sgmodule" "$YT_MODULE" || true
    - name: Clear previous JavaScriptCheck.list contents
      run: |
        > Rewrite/JavaScriptCheck.list
    - name: Process and validate local files
      run: |
        invalid_list=""
        valid_list=""
        for file in Rewrite/Chongxie.conf Rewrite/YouTubeNoAd.sgmodule Rewrite/JDPriceComparison.conf; do
          if [ -f "$file" ]; then
            echo "Processing file: $file"
            grep -Eo 'https?://[^ ]+\.(js|json)' "$file" | sort -u > Temp.list
            seen=""
            while IFS= read -r url; do
              filename=$(basename "$url")
              if echo "$seen" | grep -Fxq "$url"; then
                continue
              fi
              seen="$seen\n$url"
              if curl -fsS --output /dev/null --silent --head --fail "$url"; then
                valid_list="${valid_list}${url}\n"
              else
                invalid_list="${invalid_list}${url}\n"
              fi
            done < Temp.list
          else
            echo "$file not found"
          fi
        done
        {
          echo "[Invalid]"
          echo -e "$invalid_list"
          echo "[Valid]"
          echo -e "$valid_list"
        } > Rewrite/JavaScriptCheck.list
    - name: Commit & copy RewriteFiles
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
        message: 'Update RewriteFiles'
        add: |
          Rewrite/Chongxie.conf
          Rewrite/YouTubeNoAd.sgmodule
          Rewrite/JavaScript/*
          Rewrite/JavaScriptCheck.list
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
