name: Update RewriteFiles
on:
  schedule:
    - cron: '5 0 * * *'
  workflow_dispatch:
jobs:
  copy-links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git configuration
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Download & copy links
      run: |
        mkdir -p Rewrite/JavaScript
        LINK1="https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/chongxie.txt"
        LINK2="https://raw.githubusercontent.com/iab0x00/ProxyRules/main/Rewrite/YouTubeNoAd.sgmodule"
        curl -fsS -o "Rewrite/Chongxie.conf" "$LINK1" || true
        curl -fsS -o "Rewrite/YouTubeNoAd.sgmodule" "$LINK2" || true
        grep -Eo 'https?://[^ ]+\.(js|json)' Rewrite/Chongxie.conf Rewrite/YouTubeNoAd.sgmodule Rewrite/JDPriceComparison.conf | sort -u > Temp.list
        
        # 清空 JavaScript.list 文件，确保每次写入新的内容
        > Rewrite/JavaScript.list
        
        seen=""
        while IFS= read -r url; do
          filename=$(basename "$url")
          if echo "$seen" | grep -Fxq "$url"; then
            continue
          fi
          seen="$seen\n$url"
          
          # 使用 curl 检查文件是否成功下载并检查 HTTP 状态
          response=$(curl -fsI -w "%{http_code}" -o "Rewrite/JavaScript/$filename" "$url")
          
          # 判断 HTTP 状态码是否为 200 (下载成功)
          if [[ "$response" == "200" ]]; then
            echo "$url valid" >> Rewrite/JavaScript.list
          else
            echo "$url invalid (HTTP status: $response)" >> Rewrite/JavaScript.list
          fi
        done < Temp.list
    
    - name: Commit & copy RewriteFiles
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
        message: 'Update RewriteFiles'
        add: |
          Rewrite/Chongxie.conf
          Rewrite/YouTubeNoAd.sgmodule
          Rewrite/JavaScript/*
          Rewrite/JavaScript.list
          Rewrite/JDPriceComparison.conf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
