name: Update RewriteFiles
on:
  schedule:
    - cron: '5 0 * * *'
  workflow_dispatch:
jobs:
  copy-links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git configuration
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Download & copy links
      run: |
        mkdir -p Rewrite/JavaScript
        LINK="https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/chongxie.txt"
        curl -o "Rewrite/Chongxie.conf" "$LINK" || true
        
        # 提取 Chongxie.conf 中的 JS 文件链接
        grep -Eo 'https?://[^ ]+\.js' Rewrite/Chongxie.conf > js_links.txt

        # 下载并保存 JS 文件
        while IFS= read -r url; do
          filename=$(basename "$url")
          curl -f -o "Rewrite/JavaScript/$filename" "$url" || true
        done < js_links.txt

        # 读取 RewriteBuild.conf 文件并替换 JS 文件链接
        if [ -f "Rewrite/RewriteBuild.conf" ]; then
          while IFS= read -r line; do
            # 提取 .js 文件名
            js_file=$(echo "$line" | grep -oP 'https?://[^ ]+\.js' | basename)
            if [ -n "$js_file" ]; then
              # 如果在 Rewrite/JavaScript 中找到了该文件，就替换链接
              if [ -f "Rewrite/JavaScript/$js_file" ]; then
                new_url="https://raw.githubusercontent.com/XiangwanGuan/Shadowrocket/main/Rewrite/JavaScript/$js_file"
                # 替换 RewriteBuild.conf 中的 js 链接
                sed -i "s|$line|$new_url|g" Rewrite/RewriteBuild.conf
              fi
            fi
          done < Rewrite/RewriteBuild.conf
        fi

    - name: Commit & copy RewriteFiles
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
        message: 'Update RewriteFiles'
        add: |
          Rewrite/Chongxie.conf
          Rewrite/JavaScript/*
          Rewrite/RewriteBuild.conf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
