name: Update RewriteFiles
on:
  schedule:
    - cron: '5 0 * * *'
  workflow_dispatch:
jobs:
  copy-links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git configuration
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Download & copy links
      run: |
        mkdir -p Rewrite/JavaScript
        LINK1="https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/chongxie.txt"
        LINK2="https://raw.githubusercontent.com/iab0x00/ProxyRules/main/Rewrite/YouTubeNoAd.sgmodule"
        
        echo "Downloading $LINK1"
        curl -fsS -o "Rewrite/Chongxie.conf" "$LINK1" || echo "Failed to download $LINK1"

        echo "Downloading $LINK2"
        curl -fsS -o "Rewrite/YouTubeNoAd.sgmodule" "$LINK2" || echo "Failed to download $LINK2"
        
        # 提取所有 JS/JSON 链接并去重
        grep -Eo 'https?://[^ ]+\.(js|json)' Rewrite/Chongxie.conf Rewrite/YouTubeNoAd.sgmodule Rewrite/JDPriceComparison.conf | sort -u > Temp.list
        echo "Found the following URLs to download:"
        cat Temp.list

        > Rewrite/JavaScript/JavaScript.list
        seen=""
        
        while IFS= read -r url; do
          filename=$(basename "$url")
          
          # 防止重复下载
          if echo "$seen" | grep -Fxq "$url"; then
            echo "Skipping already seen URL: $url"
            continue
          fi
          seen="$seen\n$url"
          
          echo "Downloading file from: $url"
          if curl -fsS -o "Rewrite/JavaScript/$filename" "$url"; then
            echo "$url valid" >> Rewrite/JavaScript/JavaScript.list
          else
            echo "$url invalid (download failed)" >> Rewrite/JavaScript/JavaScript.list
          fi
        done < Temp.list
    
    - name: Commit & copy RewriteFiles
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
        message: 'Update RewriteFiles'
        add: |
          Rewrite/Chongxie.conf
          Rewrite/YouTubeNoAd.sgmodule
          Rewrite/JavaScript/*
          Rewrite/JDPriceComparison.conf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
