name: Update RewriteFiles
on:
  schedule:
    - cron: '10 0 * * *'
  workflow_dispatch:
jobs:
  copy-links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Git configuration
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - name: Define file paths and links
      run: |
        mkdir -p Rewrite/JavaScript
        echo "Rewrite/Chongxie.conf|https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/chongxie.txt" > file_links.txt
        echo "Rewrite/YouTubeNoAd.sgmodule|https://raw.githubusercontent.com/iab0x00/ProxyRules/main/Rewrite/YouTubeNoAd.sgmodule" >> file_links.txt
    - name: Download files
      run: |
        while IFS='|' read -r filepath url; do
          echo "Downloading: $url -> $filepath"
          curl -fsS -o "$filepath" "$url" || true
        done < file_links.txt
    - name: Clear previous JavaScriptCheck.md contents
      run: |
        > Rewrite/JavaScriptCheck.md
    - name: Process and validate local files
      run: |
        invalid_list=""
        valid_list=""
        files_to_check=(
          "Rewrite/Chongxie.conf"
          "Rewrite/YouTubeNoAd.sgmodule"
          "Rewrite/JDPriceComparison.conf"
        )
        for file in "${files_to_check[@]}"; do
          if [ -f "$file" ]; then
            echo "Processing file: $file"
            grep -Eo 'https?://[^ ]+\.(js|json)' "$file" | sort -u > Temp.list
            seen=""
            while IFS= read -r url; do
              if echo "$seen" | grep -Fxq "$url"; then
                continue
              fi
              seen="$seen\n$url"
              if curl -fsS --output /dev/null --silent --head --fail "$url"; then
                valid_list="${valid_list}${url}\n"
              else
                invalid_list="${invalid_list}${url}\n"
              fi
            done < Temp.list
          else
            echo "$file not found"
          fi
        done
        {
          echo "[Update]"
          echo "$(date '+%Y-%m-%d')"
          echo ""
          echo "[Invalid]"
          echo -e "$invalid_list"
          echo "[Valid]"
          echo -e "$valid_list"
        } > Rewrite/JavaScriptCheck.md
    - name: Commit & copy RewriteFiles
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
        message: 'Update RewriteFiles'
        add: |
          Rewrite/Chongxie.conf
          Rewrite/YouTubeNoAd.sgmodule
          Rewrite/JavaScript/*
          Rewrite/JavaScriptCheck.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
