name: Update RewriteFiles
on:
  schedule:
    - cron: '5 0 * * *'
  workflow_dispatch:
jobs:
  copy-links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git configuration
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Download & copy links
      run: |
        mkdir -p Rewrite/JavaScript
        LINK1="https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/chongxie.txt"
        LINK2="https://raw.githubusercontent.com/iab0x00/ProxyRules/main/Rewrite/YouTubeNoAd.sgmodule"
        curl -fsS -o "Rewrite/Chongxie.conf" "$LINK1" || true
        curl -fsS -o "Rewrite/YouTubeNoAd.sgmodule" "$LINK2" || true
        
        # 提取链接并去重
        grep -Eo 'https?://[^ ]+\.(js|json)' Rewrite/Chongxie.conf Rewrite/YouTubeNoAd.sgmodule Rewrite/JDPriceComparison.conf | sort -u > Temp.list
        > Rewrite/JavaScript/JavaScript.list
        
        seen=""
        while IFS= read -r url; do
          filename=$(basename "$url")
          
          # 检查是否已处理过该 URL
          if echo "$seen" | grep -Fxq "$url"; then
            continue
          fi
          
          seen="$seen\n$url"
          
          # 下载文件并判断其有效性
          echo "Downloading: $url"
          if curl -fsS -w "%{http_code}" -o "Rewrite/JavaScript/$filename" "$url"; then
            # 如果文件大小非零并且下载成功，则标记为 valid
            if [ -s "Rewrite/JavaScript/$filename" ]; then
              echo "$url valid" >> Rewrite/JavaScript/JavaScript.list
            else
              echo "$url invalid (empty file)" >> Rewrite/JavaScript/JavaScript.list
            fi
          else
            echo "$url invalid (download failed)" >> Rewrite/JavaScript/JavaScript.list
          fi
        done < Temp.list
    
    - name: Commit & copy RewriteFiles
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
        message: 'Update RewriteFiles'
        add: |
          Rewrite/Chongxie.conf
          Rewrite/YouTubeNoAd.sgmodule
          Rewrite/JavaScript/*
          Rewrite/JDPriceComparison.conf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
