name: Update RewriteFiles
on:
  schedule:
    - cron: '22 22 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  copy-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git configuration
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Define file paths and links
        run: |
          mkdir -p Rewrite/NaisiConfig
          mkdir -p Rewrite/JavaScript
          mkdir -p Rewrite/ZirawellConfig
          mkdir -p Rewrite/ZirawellScripts
          echo "Rewrite/NaisiConfig/QuanX.conf|https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/chongxie.txt" > rewrite_file_links.list
          echo "Rewrite/NaisiConfig/Loon.conf|https://raw.githubusercontent.com/fmz200/wool_scripts/main/Loon/plugin/blockAds.plugin" >> rewrite_file_links.list
          echo "Rewrite/NaisiConfig/Weibo.conf|https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/weibo.snippet" >> rewrite_file_links.list
          echo "Rewrite/NaisiConfig/RejectList.conf|https://raw.githubusercontent.com/fmz200/wool_scripts/refs/heads/main/Loon/rule/rejectAd.list" >> rewrite_file_links.list
          echo "Rewrite/ZirawellConfig/AllAdRewrite.conf|https://raw.githubusercontent.com/zirawell/R-Store/refs/heads/main/Rule/QuanX/Adblock/All/rewrite/allAdRewrite.conf" >> rewrite_file_links.list

      - name: Download files
        run: |
          while IFS='|' read -r filepath url; do
            echo "Downloading: $url -> $filepath"
            curl -fsS -o "$filepath" "$url" || true
          done < rewrite_file_links.list

      - name: Clear previous JavaScriptCheck.md contents
        run: |
          > Rewrite/JavaScriptCheck.md

      - name: Process and validate local files
        run: |
          invalid_list=""
          valid_list=""
          files_to_check=(
            "Rewrite/NaisiConfig/QuanX.conf"
            "Rewrite/NaisiConfig/Loon.conf"
            "Rewrite/NaisiConfig/Weibo.conf"
            "Rewrite/NaisiConfig/RejectList.conf"
            "Rewrite/AMDC.js"
            "Rewrite/ReplaceBody.js"
            "Rewrite/Amap.js"
            "Rewrite/FAWVW.js"
            "Rewrite/YouTube.conf"
          )
          declare -A downloaded_urls
          declare -A downloaded_files
          for file in "${files_to_check[@]}"; do
            if [ -f "$file" ]; then
              echo "Processing file: $file"
              if [[ "$file" == Rewrite/NaisiConfig/* ]]; then
                sed 's/#.*//' "$file" | grep -Eo 'https?://[^ ]+\.(js|json)' | sort -u > Script.list
              else
                grep -Eo 'https?://[^ ]+\.(js|json)' "$file" | sort -u > Script.list
              fi
              while IFS= read -r url; do
                if [[ "$url" =~ ^http://script.hub/convert/_start_/(.*)/_end_/.*$ ]]; then
                  raw_url="${BASH_REMATCH[1]}"
                else
                  raw_url="$url"
                fi
                if echo "$raw_url" | grep -q "https://github.com/.*/raw/"; then
                  raw_url=$(echo "$raw_url" | sed 's#https://github.com/\(.*\)/raw/\(.*\)#https://raw.githubusercontent.com/\1/\2#g')
                fi
                if echo "$raw_url" | grep -Eq "XiangwanGuan/Shadowrocket/main/Rewrite/JavaScript/"; then
                  echo "Skipping download for: $raw_url"
                  continue
                fi
                if echo "$raw_url" | grep -q "xiangwanguan.github.io/Shadowrocket/Rewrite/JavaScript/"; then
                  echo "Skipping download for: $raw_url"
                  continue
                fi
                if [[ -n "${downloaded_urls[$raw_url]}" ]]; then
                  echo "Skipping duplicate: $raw_url"
                  continue
                fi
                if curl -fsS --output /dev/null --silent --head --fail "$raw_url"; then
                  filename=$(basename "$raw_url")
                  filepath="Rewrite/JavaScript/$filename"
                  if [[ -n "${downloaded_files[$filename]}" ]]; then
                    if [[ "${downloaded_files[$filename]}" != "$raw_url" ]]; then
                      basename_noext="${filename%.*}"
                      ext="${filename##*.}"
                      filepath="Rewrite/JavaScript/${basename_noext}2.${ext}"
                    fi
                  fi
                  echo "Downloading: $raw_url -> $filepath"
                  curl -fsS -o "$filepath" "$raw_url" || true
                  valid_list="${valid_list}${raw_url}<br>\n"
                  downloaded_urls[$raw_url]=1
                  downloaded_files[$filename]="$raw_url"
                else
                  invalid_list="${invalid_list}${raw_url}<br>\n"
                fi
              done < Script.list
            else
              echo "$file not found"
            fi
          done
          {
            echo "### 更新时间：$(TZ='Asia/Shanghai' date '+%Y-%m-%d')<br>"
            echo ""
            echo "### 失效资源：<br>"
            if [[ -n "$invalid_list" ]]; then
              echo -e "$invalid_list"
            else
              echo "无失效资源！<br>"
            fi
            echo ""
            echo "### 有效资源：<br>"
            if [[ -n "$valid_list" ]]; then
              echo -e "$valid_list"
            else
              echo "无有效资源！<br>"
            fi
          } > Rewrite/JavaScriptCheck.md

      - name: Preprocess ZirawellScripts
        run: |
          file="Rewrite/ZirawellConfig/AllAdRewrite.conf"
          if [ -f "$file" ]; then
            echo "Processing ZirawellScripts for JS"
            grep -Eo 'https?://[^ ]+\.(js|json)' "$file" | sort -u > ZirawellScripts.list
            declare -A downloaded_files
            while IFS= read -r url; do
              filename=$(basename "$url")
              filepath="Rewrite/ZirawellScripts/$filename"
              if [[ -n "${downloaded_files[$filename]}" ]]; then
                if [[ "${downloaded_files[$filename]}" != "$url" ]]; then
                  basename_noext="${filename%.*}"
                  ext="${filename##*.}"
                  filepath="Rewrite/ZirawellScripts/${basename_noext}2.${ext}"
                fi
              fi
              echo "Downloading: $url -> $filepath"
              curl -fsS -o "$filepath" "$url" || true
              downloaded_files[$filename]="$url"
            done < ZirawellScripts.list
          else
            echo "$file not found"
          fi

      - name: Commit & copy RewriteFiles
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Update RewriteFiles'
          add: |
            Rewrite/NaisiConfig/*
            Rewrite/JavaScript/*
            Rewrite/ZirawellConfig/*
            Rewrite/ZirawellScripts/*
            Rewrite/JavaScriptCheck.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
