name: Update RewriteFiles
on:
  schedule:
    - cron: '5 0 * * *'
  workflow_dispatch:
jobs:
  copy-links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Git configuration
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - name: Download & copy links
      run: |
        mkdir -p Rewrite/JavaScript
        LINK="https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/chongxie.txt"
        curl -o "Rewrite/Chongxie.conf" "$LINK" || true
        grep -Eo 'https?://[^ ]+\.js' Rewrite/Chongxie.conf > js_links.txt
        > Rewrite/JavaScript/invalid_links.list
        while IFS= read -r url; do
          filename=$(basename "$url")
          if curl -f --head "$url" 2>/dev/null | grep -q "200 OK"; then
            curl -f -o "Rewrite/JavaScript/$filename" "$url" || true
          else
            echo "$url" >> Rewrite/JavaScript/invalid_links.list
          fi
        done < js_links.txt
    - name: Commit & copy RewriteFiles
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
        message: 'Update RewriteFiles'
        add: |
          Rewrite/Chongxie.conf
          Rewrite/JavaScript/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
