name: Update RewriteFiles
on:
  schedule:
    - cron: '5 0 * * *'
  workflow_dispatch:
jobs:
  copy-links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Git configuration
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - name: Download & copy links
      run: |
        mkdir -p Rewrite
        LINKS=(
          "https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/StartUp.conf"
          "https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/Bilibili.conf"
          "https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/Cainiao.conf"
        )
        for LINK in "${LINKS[@]}"; do
          FILE_NAME=$(basename $LINK)
          curl -f -o "Rewrite/$FILE_NAME" $LINK || curl -f -o "Rewrite/$FILE_NAME" $LINK
        done
    - name: Commit & copy RewriteFiles
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
        message: 'Update RewriteFiles'
        add: 'Rewrite/*'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
