name: Update RewriteFiles
on:
  schedule:
    - cron: '5 0 * * *'
  workflow_dispatch:
jobs:
  copy-links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Git configuration
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - name: Download & copy links
      run: |
        mkdir -p Rewrite/JavaScript
        LINK="https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/chongxie.txt"
        echo "Downloading $LINK"
        curl -o "Rewrite/Chongxie.conf" "$LINK" || true
        grep -Eo 'https?://[^ ]+\.js' Rewrite/Chongxie.conf > js_links.txt
        echo "Found JS links, downloading..."
        while IFS= read -r url; do
          if [ -n "$url" ]; then
            filename=$(basename "$url")
            echo "Downloading JS file: $filename"
            curl -f -o "Rewrite/JavaScript/$filename" "$url" || true
          else
            echo "Skipping empty URL"
          fi
        done < js_links.txt
        if [ -f "Rewrite/RewriteBuild.conf" ]; then
          while IFS= read -r line; do
            js_file=$(echo "$line" | grep -oP 'https?://[^ ]+\.js' | basename)
            if [ -n "$js_file" ]; then
              if [ -f "Rewrite/JavaScript/$js_file" ]; then
                new_url="https://raw.githubusercontent.com/XiangwanGuan/Shadowrocket/main/Rewrite/JavaScript/$js_file"
                echo "Updating $line to $new_url"
                sed -i "s|$line|$new_url|g" Rewrite/RewriteBuild.conf
              fi
            fi
          done < Rewrite/RewriteBuild.conf
        fi
    - name: Commit & copy RewriteFiles
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
        message: 'Update RewriteFiles'
        add: |
          Rewrite/Chongxie.conf
          Rewrite/JavaScript/*
          Rewrite/RewriteBuild.conf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
