name: Update RewriteFiles
on:
  schedule:
    - cron: '5 0 * * *'
  workflow_dispatch:
jobs:
  copy-links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git configuration
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - name: Download & copy links
      run: |
        mkdir -p Rewrite/JavaScript
        LINK="https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/chongxie.txt"
        curl -fsS -o "Rewrite/Chongxie.conf" "$LINK" || true
        grep -Eo 'https?://[^ ]+\.(js|json)' Rewrite/Chongxie.conf | sort -u > Temp.list
        > Rewrite/JavaScript/JavaScript.list
        seen=""
        while IFS= read -r url; do
          filename=$(basename "$url")
          if echo "$seen" | grep -Fxq "$url"; then
            continue
          fi
          seen="$seen\n$url"
          if curl -fsS -o "Rewrite/JavaScript/$filename" "$url"; then
            echo "$url valid" >> Rewrite/JavaScript/JavaScript.list
          else
            echo "$url invalid" >> Rewrite/JavaScript/JavaScript.list
          fi
        done < Temp.list
    - name: Commit & copy RewriteFiles
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
        message: 'Update RewriteFiles'
        add: |
          Rewrite/Chongxie.conf
          Rewrite/JavaScript/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
